{
  "client": {
    "headers": {
      "Accept": "application/vnd.github+json",
      "Authorization": "Bearer <token>",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "Prometheus"
    }
  },
  "endpoints": [
    {
      "url": "https://api.github.com/rate_limit",
      "metrics": [
        {
          "name": "github_rate_limit_core_remaining",
          "description": "Remaining core requests",
          "type": "gauge",
          "json_path": "$.resources.core.remaining",
          "labels": {
            "sensor": "cpu",
            "location": "rack1"
          }
        }
      ]
    }
  ]
}
