---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eir.fullname" . }}-endpoint-groups
  labels:
    app: {{ include "eir.name" . }}
data:
{{- range $name, $value := .Values.config.endpoint_groups }}
  {{ $name }}.json: {{ $value | toJson }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eir.fullname" . }}-contexts
  labels:
    app: {{ include "eir.name" . }}
data:
{{- range $name, $value := .Values.config.contexts }}
  {{ $name }}.json: {{ $value | toJson }}
{{- end }}
