---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eir.fullname" . }}-endpoint-groups
  labels:
    app: {{ include "eir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
data:
{{- range $name, $value := .Values.config.endpoint_groups }}
  {{ $name }}.json: {{ $value | toJson | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eir.fullname" . }}-contexts
  labels:
    app: {{ include "eir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
data:
{{- range $name, $value := .Values.config.contexts }}
  {{ $name }}.json: {{ $value | toJson | quote }}
{{- end }}
