apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eir.fullname" . }}-clients
  labels:
    app: {{ include "eir.name" . }}
type: Opaque
data:
{{- range $name, $client := .Values.config.clients }}
  {{ $name }}.json: {{ $client | toJson | b64enc }}
{{- end }}
