image:
  repository: eir
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

env: []

config:
  clients: 
    main:
      headers:
        Accept: application/vnd.github+json
        Authorization: Bearer <token>
        X-GitHub-Api-Version: 2022-11-28
        User-Agent: Prometheus
      max_connections: 10
  endpoint_groups:
    github:
      url: https://api.github.com/rate_limit
      interval: 1m
      metrics:
        - name: github_rate_limit_core_remaining
          description: Remaining core requests
          type: gauge
          value: jmespath:response.json.resources.core.remaining
          labels:
            - name: static
              value: some_static_value
        - name: github_token_expiration
          description: Token expiration time in seconds
          type: gauge
          value: jmespath:to_timestamp(replace(response.headers."github-authentication-token-expiration", 'UTC', '+00:00'), '%Y-%m-%d %H:%M:%S %z')
          labels:
            - name: static
              value: some_static_value
    contexts:
      main:
        client: main
        endpoint_groups:
          - github
